spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/smartgame?createDatabaseIfNotExist=true
    username: root
    password: fs1lm3gl5tt
  jackson:
    default-property-inclusion: non_null  #driver-class-name: com.mysql.cj.jdbc.Driver
